version: "3.8" # Ensure you're using version 3.8 or later

services:
  postgres:
    image: postgres:15 # Use a specific PostgreSQL version
    container_name: tennistime_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tennistime_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devops_app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: tennistime_redis
    ports:
      - "6379:6379"
    networks:
      - devops_app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  smtp:
    image: mailhog/mailhog
    container_name: tennistime_smtp
    ports:
      - "2525:2525" # SMTP port
      - "8025:8025" # Web UI for MailHog
    networks:
      - devops_app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: registry.gitlab.com/miladfahimi2012/tennistime/backend:latest
    ports:
      - "8090:8090"
    networks:
      - devops_app-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  authentication:
    image: registry.gitlab.com/miladfahimi2012/tennistime/authentication:latest
    ports:
      - "8095:8095"
    networks:
      - devops_app-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8095/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  bff:
    image: registry.gitlab.com/miladfahimi2012/tennistime/bff:latest
    ports:
      - "8089:8089"
    networks:
      - devops_app-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  profile:
    image: registry.gitlab.com/miladfahimi2012/tennistime/profile:latest
    ports:
      - "8099:8099"
    networks:
      - devops_app-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8099/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  reservation:
    image: registry.gitlab.com/miladfahimi2012/tennistime/reservation:latest
    ports:
      - "8085:8085"
    networks:
      - devops_app-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev,docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: registry.gitlab.com/miladfahimi2012/tennistime/frontend:latest
    container_name: tennistime_nginx
    ports:
      - "4200:80" # Expose Nginx on port 4200
    volumes:
      - ./frontend/www:/usr/share/nginx/html # Serve frontend dynamically from this volume
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:type=bind
    networks:
      - devops_app-network
    depends_on:
      - backend
      - authentication
      - bff
      - profile
      - reservation

networks:
  devops_app-network:
    name: devops_app-network

volumes:
  postgres_data:
