version: "3.8" # Ensure you're using version 3.8 or later

services:
  postgres:
    image: postgres:15 # Use a specific PostgreSQL version
    container_name: postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tennistime_test
    volumes:
      - /home/TennisTime/tennistime/postgres_data:/var/lib/postgresql/data
    networks:
      - app_network_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis_test
    networks:
      - app_network_test
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  smtp:
    build:
      context: /home/TennisTime/tennistime/FakeSMTP
      dockerfile: Dockerfile
    container_name: smtp_test
    ports:
      - "8025:8025"
    networks:
      - app_network_test
    volumes:
      - /home/TennisTime/tennistime/FakeSMTP/target:/app/target

  provider:
    build:
      context: /home/TennisTime/tennistime/provider
      dockerfile: Dockerfile.test
    container_name: provider_test
    volumes:
      - /home/TennisTime/tennistime/provider/src:/app/src
      - /home/TennisTime/tennistime/provider/target:/app/target
      - /home/TennisTime/tennistime/provider/pom.xml:/app/pom.xml
    networks:
      - app_network_test
    ports:
      - "8086:8086"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: test
      DB_HOST: postgres
      DB_PORT: 5432
      jwt.secret: Dy64nBQfRKEQtLTRDV42R8/H3XsxVFFk+zrXb2l+PQz8j+p5vR+RYAkfLK+jXdhmRrx3gU8yU9TcvKjL43FUYw==
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  authentication:
    build:
      context: /home/TennisTime/tennistime/authentication
      dockerfile: Dockerfile.test
    container_name: authentication_test
    volumes:
      - /home/TennisTime/tennistime/authentication/src:/app/src
      - /home/TennisTime/tennistime/authentication/target:/app/target
      - /home/TennisTime/tennistime/authentication/pom.xml:/app/pom.xml
    networks:
      - app_network_test
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: test
      DB_HOST: postgres
      DB_PORT: 5432
      jwt.secret: Dy64nBQfRKEQtLTRDV42R8/H3XsxVFFk+zrXb2l+PQz8j+p5vR+RYAkfLK+jXdhmRrx3gU8yU9TcvKjL43FUYw==

    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  bff:
    build:
      context: /home/TennisTime/tennistime/bff
      dockerfile: Dockerfile.test
    container_name: bff_test
    volumes:
      - /home/TennisTime/tennistime/bff/src:/app/src
      - /home/TennisTime/tennistime/bff/target:/app/target
      - /home/TennisTime/tennistime/bff/pom.xml:/app/pom.xml
    networks:
      - app_network_test
    ports:
      - "8083:8083"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: test
      DB_HOST: postgres
      DB_PORT: 5432
      jwt.secret: Dy64nBQfRKEQtLTRDV42R8/H3XsxVFFk+zrXb2l+PQz8j+p5vR+RYAkfLK+jXdhmRrx3gU8yU9TcvKjL43FUYw==

    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  profile:
    build:
      context: /home/TennisTime/tennistime/profile
      dockerfile: Dockerfile.test
    container_name: profile_test
    volumes:
      - /home/TennisTime/tennistime/profile/src:/app/src
      - /home/TennisTime/tennistime/profile/target:/app/target
      - /home/TennisTime/tennistime/profile/pom.xml:/app/pom.xml
    networks:
      - app_network_test
    ports:
      - "8084:8084"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: test
      DB_HOST: postgres
      DB_PORT: 5432
      jwt.secret: Dy64nBQfRKEQtLTRDV42R8/H3XsxVFFk+zrXb2l+PQz8j+p5vR+RYAkfLK+jXdhmRrx3gU8yU9TcvKjL43FUYw==

    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8084/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  reservation:
    build:
      context: /home/TennisTime/tennistime/reservation
      dockerfile: Dockerfile.test
    container_name: reservation_test
    volumes:
      - /home/TennisTime/tennistime/reservation/src:/app/src
      - /home/TennisTime/tennistime/reservation/target:/app/target
      - /home/TennisTime/tennistime/reservation/pom.xml:/app/pom.xml
    networks:
      - app_network_test
    ports:
      - "8085:8085"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: test
      DB_HOST: postgres
      DB_PORT: 5432
      jwt.secret: Dy64nBQfRKEQtLTRDV42R8/H3XsxVFFk+zrXb2l+PQz8j+p5vR+RYAkfLK+jXdhmRrx3gU8yU9TcvKjL43FUYw==

    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: /home/TennisTime/tennistime/frontend
      dockerfile: Dockerfile.test
    container_name: nginx_test
    volumes:
      - /home/TennisTime/tennistime/frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_network_test
    ports:
      - "8080:80"
    depends_on:
      - provider
      - authentication
      - bff
      - profile
      - reservation
    environment:
      - NODE_ENV=production

networks:
  app_network_test:
    name: app_network_test

volumes:
  postgres_data:
