version: "3.8"

services:
  backend:
    build:
      context: ../backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ../frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "4200:4200"
