version: "3.8"

services:
  authentication:
    image: registry.gitlab.com/yourusername/yourproject/authentication:latest
    restart: always
    ports:
      - "8095:8080" # Host:Container
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  backend:
    image: registry.gitlab.com/yourusername/yourproject/backend:latest
    restart: always
    ports:
      - "8090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  bff:
    image: registry.gitlab.com/yourusername/yourproject/bff:latest
    restart: always
    ports:
      - "8089:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  frontend:
    image: registry.gitlab.com/yourusername/yourproject/frontend:latest
    restart: always
    ports:
      - "80:8080" # Frontend commonly uses port 80
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  profile:
    image: registry.gitlab.com/yourusername/yourproject/profile:latest
    restart: always
    ports:
      - "8099:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  reservation:
    image: registry.gitlab.com/yourusername/yourproject/reservation:latest
    restart: always
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
