services:
  authentication:
    build:
      context: ../authentication
      dockerfile: Dockerfile
    image: tennistime/authentication:latest
    ports:
      - "8080:8080"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: tennistime/backend:latest
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - authentication
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  bff:
    build:
      context: ../bff
      dockerfile: Dockerfile
    image: tennistime/bff:latest
    ports:
      - "8082:8080"
    networks:
      - app-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  profile:
    build:
      context: ../profile
      dockerfile: Dockerfile
    image: tennistime/profile:latest
    ports:
      - "8083:8080"
    networks:
      - app-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  reservation:
    build:
      context: ../reservation
      dockerfile: Dockerfile
    image: tennistime/reservation:latest
    ports:
      - "8084:8080"
    networks:
      - app-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge
