package com.tennistime.bff.application.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.UUID;

/**
 * Data Transfer Object representing a reservation in the application layer.
 * <p>
 * DDD note: This DTO belongs to the Application layer and is used for transport between
 * the BFF and external clients/services. Domain invariants and business rules should be
 * enforced in the Domain layer; this DTO intentionally contains no behavior.
 * </p>
 *
 * <p>
 * Time fields accept both "HH:mm" and "HH:mm:ss" (and optional milliseconds) to be resilient
 * against upstream variations, avoiding deserialization errors like:
 * {@code java.time.format.DateTimeParseException: Text '14:00:00' could not be parsed}.
 * </p>
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ReservationDTO {

    /** Unique identifier of the reservation (generated by the system). */
    @Schema(hidden = true)
    private UUID id;

    /** Gregorian reservation date in ISO-8601 format (yyyy-MM-dd). */
    @Schema(example = "2024-08-05", description = "Reservation date in ISO format (Gregorian).")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate reservationDate;

    /** Persian (Jalali) date as a plain string for display purposes. */
    @Schema(example = "1403-04-01", description = "Reservation date in Persian (Jalali) calendar as a string.")
    private String reservationDatePersian;

    /**
     * Reservation start time.
     * <p>
     * Accepts "HH:mm", "HH:mm:ss", and "HH:mm:ss.SSS".
     * The optional sections are expressed via bracket notation in the pattern.
     * </p>
     */
    @Schema(example = "10:00", description = "Start time. Accepts HH:mm or HH:mm:ss.")
    @JsonFormat(pattern = "HH:mm[:ss[.SSS]]")
    private LocalTime startTime;

    /**
     * Reservation end time.
     * <p>
     * Accepts "HH:mm", "HH:mm:ss", and "HH:mm:ss.SSS".
     * </p>
     */
    @Schema(example = "12:00", description = "End time. Accepts HH:mm or HH:mm:ss.")
    @JsonFormat(pattern = "HH:mm[:ss[.SSS]]")
    private LocalTime endTime;

    /** Reservation status (e.g., pending, confirmed, cancelled). */
    @Schema(example = "confirmed", description = "Reservation status.")
    private String status;

    /** Identifier of the user who made the reservation. */
    @Schema(example = "d290f1ee-6c54-4b01-90e6-d701748f0851", description = "User ID.")
    private UUID userId;

    /** Identifier of the provider offering the service. */
    @Schema(example = "d290f1ee-6c54-4b01-90e6-d701733344441", description = "Provider ID.")
    private UUID providerId;

    /** Identifier of the service being reserved. */
    @Schema(example = "d290f1ee-6c54-4b01-90e6-d70173333331", description = "Service ID.")
    private UUID serviceId;
}
